const MIN_VALID_PDF_BYTES = 5 * 1024;
const MIN_PDF_BYTES = 1024;

function decodePdf(data) {
  try {
    return atob(data || "");
  } catch (_) {
    throw new Error("PDF 데이터가 손상되어 저장하지 않았습니다.");
  }
}

function validatePdf(data, strict = false) {
  const raw = decodePdf(data);
  console.info("[Hakdol PDF] generated bytes:", raw.length);
  const validStructure = raw.startsWith("%PDF-") && /%%EOF\s*$/.test(raw) && raw.length >= MIN_PDF_BYTES;
  const explicitText = /BT[\s\S]{1,8000}(?:Tj|TJ)[\s\S]{0,8000}ET/.test(raw);
  if (!validStructure || (strict && raw.length < MIN_VALID_PDF_BYTES && !explicitText)) {
    console.info("[Hakdol PDF] invalid PDF detected");
    throw new Error("세금계산서 내용을 PDF로 만들지 못했습니다. 사이트의 출력 방식을 다시 확인해주세요.");
  }
  return raw.length;
}

async function screenshotPdf(data, orientation = "auto") {
  const raw = atob(data || "");
  const bytes = Uint8Array.from(raw, (character) => character.charCodeAt(0));
  const bitmap = await createImageBitmap(new Blob([bytes], { type: "image/jpeg" }));
  const width = bitmap.width;
  const height = bitmap.height;
  const canvas = new OffscreenCanvas(128, 128);
  const context = canvas.getContext("2d", { willReadFrequently: true });
  context.drawImage(bitmap, 0, 0, 128, 128);
  bitmap.close();
  const pixels = context.getImageData(0, 0, 128, 128).data;
  let dark = 0;
  let minimum = 255;
  let maximum = 0;
  for (let index = 0; index < pixels.length; index += 4) {
    const luminance = (pixels[index] + pixels[index + 1] + pixels[index + 2]) / 3;
    if (luminance < 230) dark += 1;
    minimum = Math.min(minimum, luminance);
    maximum = Math.max(maximum, luminance);
  }
  if (maximum - minimum < 20 || dark < 32) {
    throw new Error("빈 화면이 감지되어 PDF를 저장하지 않았습니다.");
  }

  const landscape = orientation === "landscape" || (orientation === "auto" && width > height * 1.2);
  const pageWidth = landscape ? 842 : 595;
  const pageHeight = landscape ? 595 : 842;
  const scale = Math.min((pageWidth - 32) / width, (pageHeight - 32) / height);
  if (scale < 0.35) {
    throw new Error("계산서가 너무 길어 한 페이지로 저장하면 읽기 어렵습니다. 사이트의 인쇄 기능을 이용해주세요.");
  }
  const renderedWidth = width * scale;
  const renderedHeight = height * scale;
  const content = `q ${renderedWidth} 0 0 ${renderedHeight} ${(pageWidth - renderedWidth) / 2} ${pageHeight - 16 - renderedHeight} cm /Im0 Do Q`;
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`,
    `<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${raw.length} >>\nstream\n${raw}\nendstream`,
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`
  ];
  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const crossReference = pdf.length;
  pdf += "xref\n0 6\n0000000000 65535 f \n";
  pdf += offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("");
  pdf += `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${crossReference}\n%%EOF\n`;
  return btoa(pdf);
}
